theme: jekyll-theme-cayman
name: The things that shouldn't be
title: The things that shouldn't be
# description: Where I post development stuff
url: "https://www.marconcini.dev"


# Midnight Theme exclusive?
show_downloads: false

exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
